LOGIN = "batal990@mail.ru"
PASSWORD = "9Gq*686vJcYRtK"
URL = "https://target-sandbox.my.com/"
INVALID_EMAIL = "battal@mail.ru"
INVALID_PASSWORD = "12345"
VK_EDUCATION = "https://vk.com/vkedu"
URL_DASHBOARD = "https://target-sandbox.my.com/dashboard"
